// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrydobyinduhwvhfpgvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeWRvYnlpbmR1aHd2aGZwZ3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDAyMDEsImV4cCI6MjA2MzcxNjIwMX0.FqcpMGfjb7cqtmQbuKeilEbtpi_TJVTPJTA-AjQd7pY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);